# Generated by Django 3.0.5 on 2020-09-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp', '0002_word_hira'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='ex_sent',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
